export enum Cities {
  NewYork = "New York",
  LosAngeles = "Los Angeles",
  Chicago = "Chicago",
  Houston = "Houston",
  Phoenix = "Phoenix",
  London = "London",
  Berlin = "Berlin",
  Paris = "Paris",
  Tokyo = "Tokyo",
  Beijing = "Beijing",
  Sydney = "Sydney",
  Toronto = "Toronto",
  Moscow = "Moscow",
  RioDeJaneiro = "Rio de Janeiro",
  CapeTown = "Cape Town",
  Mumbai = "Mumbai",
  Dubai = "Dubai",
  Bangkok = "Bangkok",
  Singapore = "Singapore",
  Istanbul = "Istanbul",
  Lahore = "Lahore",
  Islamabad = "Islamabad",
}
